name: Exch CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
    - uses: chartboost/ruff-action@v1
      with:
        fix_args: --fix .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry env use python3.11
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry install
        source .venv/bin/activate
    - name: Build coverage file
      run: |
        pytest tests --slow --cov=. test/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
